version: "3.9"


services:
  db:
    image: postgres:14.2-alpine
    restart: always
    env_file: .db.env
    ports:
      - 5432:5432
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5


  migration:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./migrations
    env_file: .db.env
    entrypoint: /app/migrate
    networks:
      - backend
    volumes:
      - ./migrations:/app

networks:
  backend:
