version: "3.9"

services:
  db:
    build:
      dockerfile: Dockerfile.db
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - never

  db-prod:
    extends:
      service: db
    env_file: .db-prod.env
    networks:
      - backend-prod
    profiles:
      - prod

  db-dev:
    extends:
      service: db
    env_file: .db-dev.env
    networks:
      - backend-dev
    profiles:
      - dev

  db-test:
    extends:
      service: db
    env_file: .db-test.env
    networks:
      - backend-test
    profiles:
      - test

  migration:
    build:
      context: ./migrations
    working_dir: /usr/app
    entrypoint: ./migrate
    volumes:
      - ./migrations:/usr/app
    profiles:
      - never

  migration-prod:
    depends_on:
      db-prod:
        condition: service_healthy
    extends:
      service: migration
    env_file: .db-prod.env
    networks:
      - backend-prod
    profiles:
      - prod

  migration-dev:
    depends_on:
      db-dev:
        condition: service_healthy
    extends:
      service: migration
    env_file: .db-dev.env
    networks:
      - backend-dev
    profiles:
      - dev

  migration-test:
    depends_on:
      db-test:
        condition: service_healthy
    extends:
      service: migration
    env_file: .db-test.env
    networks:
      - backend-test
    profiles:
      - test

  mock-redis:
    image: redis:6.2.6-alpine3.15
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./mock-redis.conf:/usr/local/etc/redis/redis.conf:ro

  mock-redis-dev:
    extends:
      service: mock-redis
    ports:
      - 6379:6379
    networks:
      - backend-dev
    profiles:
      - dev

  mock-redis-test:
    extends:
      service: mock-redis
    ports:
      - 6379:6379
    networks:
      - backend-test
    profiles:
      - test

  mock-redis-prod:
    extends:
      service: mock-redis
    ports:
      - 6379:6379
    networks:
      - backend-prod
    profiles:
      - prod

  mock-notifier:
    build:
      dockerfile: services/mock_notifier/Dockerfile
    ports:
      - 3000:3000
    profiles:
      - never

  mock-notifier-prod:
    extends:
      service: mock-notifier
    depends_on:
      - mock-redis-prod
    networks:
      - backend-prod
    profiles:
      - prod

  mock-notifier-dev:
    extends:
      service: mock-notifier
    depends_on:
      - mock-redis-dev
    env_file: .mock-notifier-dev.env
    networks:
      - backend-dev
    profiles:
      - dev

  mock-notifier-test:
    extends:
      service: mock-notifier
    depends_on:
      - mock-redis-test
    env_file: .mock-notifier-test.env
    networks:
      - backend-test
    profiles:
      - test

networks:
  backend-dev:
  backend-test:
  backend-prod:
