version: "3.9"

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    env_file: .db.env
    ports:
      - 5432:5432
    networks:
      - backend
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./migrations
    working_dir: /usr/app
    env_file: .db.env
    entrypoint: ./migrate
    networks:
      - backend
    volumes:
      - ./migrations:/usr/app

  server-dev:
    depends_on:
      migration:
        condition: service_completed_successfully
    image: cosmtrek/air:v1.29.0
    working_dir: /usr/app
    env_file: .server.env
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./:/usr/app
    profiles:
      - dev

networks:
  backend:
