version: "3.9"

services:
  db:
    build:
      dockerfile: Dockerfile.db
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - never

  db-prod:
    extends:
      service: db
    env_file: .db-prod.env
    profiles:
      - prod

  db-dev:
    extends:
      service: db
    env_file: .db-dev.env
    profiles:
      - dev

  db-test:
    extends:
      service: db
    env_file: .db-test.env
    profiles:
      - test

  migration:
    build:
      context: ./migrations
    working_dir: /usr/app
    entrypoint: ./migrate
    networks:
      - backend
    volumes:
      - ./migrations:/usr/app
    profiles:
      - never

  migration-prod:
    depends_on:
      db-prod:
        condition: service_healthy
    extends:
      service: migration
    env_file: .db-prod.env
    profiles:
      - prod

  migration-dev:
    depends_on:
      db-dev:
        condition: service_healthy
    extends:
      service: migration
    env_file: .db-dev.env
    profiles:
      - dev

  migration-test:
    depends_on:
      db-test:
        condition: service_healthy
    extends:
      service: migration
    env_file: .db-test.env
    profiles:
      - test

networks:
  backend:
