version: '3'
# https://taskfile.dev/#/installation

tasks:
  gqlgen:
    desc: Generate code for GraphQL schema
    cmds:
      - go run github.com/99designs/gqlgen generate
    sources:
      - gqlgen.yml
      - db/**/*.resolvers.go
      - graph/*.go
      - graph/model/**/*.go
      - graph/schema/**/*.graphqls
    generates:
      - graph/generated/generated.go
      - graph/model/models_gen.go

  grpcgen:
    desc: Generate code for grpc
    cmds:
      - PATH=$PATH:$(go env GOPATH)/bin protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative grpc/**/*.proto
    sources:
      - grpc/**/*.proto
    generates:
      - grpc/**/*.pb.go

  build:mock_notifier:
    desc: Builds image of mock_notifier service
    sources:
      - grpc/notifier/*.go
      - services/mock_notifier/*
    cmds:
      - docker-compose build mock-notifier

  dev:
    desc: Start dev server
    deps:
      - build:mock_notifier
    env:
      SERVER_DOTENV: .server-dev.env
    cmds: 
      - docker-compose --profile dev up -d
      - defer: docker-compose --profile dev stop
      - docker logs -f auction-mock-notifier-dev-1 &
      - air
  
  dir:out:
    desc: Creates out directiory
    cmds:
      - mkdir -p out
    status:
      - test -d out
  
  filter-cover:
    desc: Filters generated files from coverage output
    cmds:
      - cat {{.IN}} | grep -v "_gen.go\|_suite.go\|generated.go\|.pb.go" > {{.OUT}}

  test:unit:
    desc: Get code coverage by unit tests
    deps:
      - dir:out
    vars:
      TMPOUT: ./out/unit-coverage.tmp.out
      OUT: ./out/unit-coverage.out
      HTML: ./out/unit-coverage.html
    cmds:
      - go test -coverprofile={{.TMPOUT}} ./...
      # remove generated code from coverage
      - task: filter-cover
        vars:
          IN: "{{.TMPOUT}}"
          OUT: "{{.OUT}}"
      - go tool cover -func={{.OUT}}
      - go tool cover -html={{.OUT}} -o {{.HTML}}

  test:it:
    desc: Get code coverage by integration tests
    deps:
      - dir:out
      - build:mock_notifier
    env:
      SERVER_DOTENV: .server-test.env
      GIN_MODE: debug
    vars:
      TMPOUT: ./out/it-coverage.tmp.out
      OUT: ./out/it-coverage.out
      HTML: ./out/it-coverage.html
    cmds:
      - docker-compose --profile test up --force-recreate -d
      - defer: docker-compose --profile test down
      - go test -tags=integration -coverprofile={{.TMPOUT}} -coverpkg="auction-back/..." 
      - task: filter-cover
        vars:
          IN: "{{.TMPOUT}}"
          OUT: "{{.OUT}}"
      - go tool cover -func={{.OUT}}
      - go tool cover -html={{.OUT}} -o {{.HTML}}
